
# Pranjal Arch Hyprland

monitor=,preferred,auto,1.25


# Variables
$terminal = alacritty
$fileManager = thunar
$menu = rofi -show drun


# Animations
source = hyprland/rules.conf
source = hyprland/prefs.conf
source = hyprland/input.conf
source = hyprland/theme.conf
source = hyprland/env.conf
source = hyprland/exec.conf
source = hyprland/animation.conf
source = hyprland/keybind.conf
