# EXEC

exec-once = /usr/lib/xdg-desktop-portal 
exec-once = /usr/lib/xdg-desktop-portal-gtk 
exec-once = /usr/lib/xdg-desktop-portal-hyprland 
exec-once = systemctl --user start hyprpolkitagent 
exec-once = hyprpaper
exec-once = hypridle 
exec-once = waybar 
exec-once = python3 /home/pranjal/accel.py

