# EXEC

exec-once = /usr/lib/xdg-desktop-portal 
exec-once = /usr/lib/xdg-desktop-portal-gtk 
exec-once = /usr/lib/xdg-desktop-portal-hyprland 
exec-once = systemctl --user start hyprpolkitagent 
exec-once = swaybg -i $HOME/Pictures/Downloaded/Mountains.jpg
exec-once = hypridle 
exec-once = waybar --config $HOME/.config/waybar/config-hypr.jsonc


